FROM rancher/rancher:v2.6.0-linux-arm64
RUN zypper -nq in libpython3_6m1_0 python3 python3-base \
    python3-appdirs python3-packaging python3-pip \
    python3-pyparsing python3-setuptools python3-six
RUN pip install -qqq balena-sdk
RUN mkdir /balena 
COPY . ./balena/
RUN chmod +x start.sh
CMD ["/bin/bash", "start.sh"]