FROM rancher/rancher:v2.6.0-linux-arm64
RUN zypper -nq in libpython3_6m1_0 python3 python3-base \
    python3-appdirs python3-packaging python3-pip \
    python3-pyparsing python3-setuptools python3-six
RUN pip install -qqq balena-sdk
RUN mkdir /balena 
COPY ./token-wrangler.py /balena/token-wrangler.py
RUN sed -i '2 a python3 /balena/token-wrangler.py & \n' /usr/bin/entrypoint.sh