version: '2'
services:
  rancher:
    image: rancher/rancher:v2.6.0-linux-arm64
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - CATTLE_BOOTSTRAP_PASSWORD=b@13n4!
    network_mode: host